new version from texlive
git-svn-id: https://serveur-svn.lri.fr/svn/modhel/luatex/trunk@1386 0b2b3880-5936-4365-a048-eb17d2e5a6bf

diff --git a/src/texk/kpathsea/mktexpk b/src/texk/kpathsea/mktexpk
--- a/src/texk/kpathsea/mktexpk
+++ b/src/texk/kpathsea/mktexpk
@@ -4,7 +4,8 @@
 # (If you change or delete the word `original' on the previous line,
 # installation won't write this script over yours.)
 # 
-# te@dbs.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
+# Originally written by Thomas Esser, Karl Berry, and Olaf Weber.
+# Report bugs to tex-k@tug.org.
 # Public domain.
 
 version='$Id: mktexpk,v 1.34 2005/06/21 10:49:10 olaf Exp $'
@@ -119,7 +120,7 @@ if kpsewhich $NAME.mf >/dev/null 2>&1 || mktexmf $NAME >/dev/null 2>&1; then
      360) MODE=epstylus;;
      400) MODE=nexthi;;
      600) MODE=ljfour;;
-     720) MODE=epsczz;;
+     720) MODE=epscszz;;
     1200) MODE=ultre;;
     1270) MODE=linoone;;
     8000) MODE=dpdfezzz;;
@@ -212,7 +213,7 @@ fi
 
 "$MT_MKTEXDIR" "$PKDESTDIR"
 if test ! -d "$PKDESTDIR"; then
-  echo "$progname: mktexdir $PKDESTDIR failed." >&2
+  echo "$progname: $MT_MKTEXDIR $PKDESTDIR failed." >&2
   exit 1
 fi
 
@@ -250,7 +251,7 @@ fi
 # Use cp when mv fails, since DOS will fail mv for deeply-nested directories.
 mv $PKNAME "$PKDESTDIR/pk$$.tmp" 2>/dev/null \
   || cp $PKNAME "$PKDESTDIR/pk$$.tmp" || exit 1
-cd $PKDESTDIR || exit 1
+cd "$PKDESTDIR" || exit 1
 chmod `kpsestat -xst,go-w .` pk$$.tmp
 test -r $PKNAME || mv pk$$.tmp $PKNAME || exit 1
 
