import new kpathsea, web2c, lib and build structure from texlive
git-svn-id: https://serveur-svn.lri.fr/svn/modhel/luatex/trunk@3510 0b2b3880-5936-4365-a048-eb17d2e5a6bf

diff --git a/source/texk/Makefile.am b/source/texk/Makefile.am
--- a/source/texk/Makefile.am
+++ b/source/texk/Makefile.am
@@ -1,23 +1,20 @@
 ## Makefile.am for the TeX Live subdirectory texk/
 ##
-## Copyright (C) 2009 Peter Breitenlohner <tex-live@tug.org>
+## Copyright (C) 2009, 2010 Peter Breitenlohner <tex-live@tug.org>
 ## You may freely use, modify and/or distribute this file.
 ##
 ## Use 'aclocal --force' (for "computed m4_sinclude")
 ##
 ACLOCAL_AMFLAGS = -I ../m4 --force
 
-SUBDIRS = dummy . $(SUBTEXK)
-DIST_SUBDIRS = dummy $(DIST_SUBTEXK)
+SUBDIRS = . $(SUBTEXK)
+DIST_SUBDIRS = $(DIST_SUBTEXK)
 
 # just in case a subdirectory has added directories
 dist-hook:
 	rm -rf `find $(distdir) -name .svn`
 
-SUBTEXK_AUX = subtexkdir-configure subtexkdir-conf.args
-noinst_DATA = $(SUBTEXK_AUX)
-
-DISTCLEANFILES = $(noinst_DATA)
+CONFIG_AUX = ../subsubdir-conf.cmd
 
 all-local: subtexk
 
@@ -29,8 +26,8 @@ all-local: subtexk
 #
 # Sequentially configure and optionally build all texk subdirs;
 # code inspired by automake's way to handle recursive targets.
-subtexk: $(noinst_DATA)
-	@failcom='exit 1'; \
+subtexk: $(CONFIG_AUX)
+	@fail= failcom='exit 1'; \
 	for f in x $$MAKEFLAGS; do \
 	  case $$f in \
 	    *=* | --[!k]*);; \
@@ -40,14 +37,16 @@ subtexk: $(noinst_DATA)
 	list='$(DIST_SUBTEXK)'; for subtexk in $$list; do \
 	  if test ! -f $$subtexk/Makefile; then \
 	    test -d $$subtexk || $(MKDIR_P) $$subtexk; \
-	    cmd=`cat $(SUBTEXK_AUX) | sed "s,SUBTEXKDIR,$$subtexk,g"`; \
+	    cmd=`cat $(CONFIG_AUX) | sed "s,auxdir/auxsub,texk/$$subtexk,g"`; \
 	    case " $(SUBTEXK) " in \
 	      *" $$subtexk "*) skip=;; \
 	      *) skip=' --disable-build';; \
 	    esac; \
 	    (cd $$subtexk && echo "=== configuring in $$subtexk (`pwd`)" && \
 	      echo "make: running $(SHELL) $$cmd$$skip" && \
-	      eval $(SHELL) $$cmd$$skip) && \
+	      CONFIG_SHELL=$(SHELL) && export CONFIG_SHELL && \
+	      eval $(SHELL) $$cmd$$skip || \
+	        { echo "=== configuring in $$subtexk failed"; exit 1; }) && \
 	    if test "x$$skip" = x; then \
 	      echo "Making all in $$subtexk" && \
 	      (cd $$subtexk && $(MAKE) $(AM_MAKEFLAGS) all); \
@@ -55,11 +54,16 @@ subtexk: $(noinst_DATA)
 	  fi; \
 	done; test -z "$$fail"
 
-subtexkdir-configure:
-	@echo "make in ./dummy failed to create the file $@"
+../subsubdir-conf.cmd:
+	@echo "configure in ../auxdir/auxsub failed to create the file $@"
 	exit 1
 
-subtexkdir-conf.args:
-	@echo "configure in ./dummy failed to create the file $@"
-	exit 1
+# Common infrastructure for tests
+EXTRA_DIST = tests
 
+# Special target to run TRIP and TRAP tests and create diffs.
+.PHONY: triptrap
+triptrap: web2c/Makefile
+	cd web2c && $(MAKE) $(AM_MAKEFLAGS) $@
+web2c/Makefile:
+	$(MAKE) $(AM_MAKEFLAGS) DIST_SUBTEXK=web2c subtexk
