infrastructure updates from TL
git-svn-id: https://serveur-svn.lri.fr/svn/modhel/luatex/branches/experimental@4778 0b2b3880-5936-4365-a048-eb17d2e5a6bf

diff --git a/source/texk/web2c/triptrap-sh b/source/texk/web2c/triptrap-sh
--- a/source/texk/web2c/triptrap-sh
+++ b/source/texk/web2c/triptrap-sh
@@ -16,29 +16,38 @@ tmp=$me.$$
 trap "rm -f $tmp" 1 2 13 15
 
 echo "$me: Running TRIP and TRAP tests and creating diffs."
+rc=0
 for file
 do
   case $file in
-  trip.diffs) tst=trip; msg='TRIP test for TeX';;
-  mftrap.diffs) tst=trap; msg='TRAP test for Metafont';;
-  mptrap.diffs) tst=mplibdir/mptrap; msg='MPTRAP test for MetaPost';;
-  etrip.diffs) tst=etexdir/etrip; msg='e-TRIP test for e-TeX';;
-  ptrip.diffs) tst=ptexdir/ptrip; msg='TRIP test for pTeX';;
-  eptrip.diffs) tst=eptexdir/eptrip; msg='e-TRIP test for e-pTeX';;
-  uptrip.diffs) tst=uptexdir/uptrip; msg='TRIP test for upTeX';;
-  euptrip.diffs) tst=euptexdir/euptrip; msg='e-TRIP test for e-upTeX';;
+  trip.diffs) tst=triptest; msg='TRIP test for TeX';;
+  mftrap.diffs) tst=mftraptest; msg='TRAP test for Metafont';;
+  mptrap.diffs) tst=mplibdir/mptraptest; msg='MPTRAP test for MetaPost';;
+  etrip.diffs) tst=etexdir/etriptest; msg='e-TRIP test for e-TeX';;
+  ptrip.diffs) tst=ptexdir/ptriptest; msg='TRIP test for pTeX';;
+  eptrip.diffs) tst=eptexdir/eptriptest; msg='e-TRIP test for e-pTeX';;
+  uptrip.diffs) tst=uptexdir/uptriptest; msg='TRIP test for upTeX';;
+  euptrip.diffs) tst=euptexdir/euptriptest; msg='e-TRIP test for e-upTeX';;
   *) echo "$me: Bad argument \`$file'"; exit 1;;
   esac
   echo ">>> Running $msg."
-  $MAKE TESTS=$tst.test check-am >$tmp 2>&1 \
-    && grep "PASS: $tst\.test" $tmp >/dev/null 2>&1 \
-    || { echo "FAIL: $tst.test"; exit 1; }
+  is_OK=:
+  $MAKE TESTS=$tst check-am >$tmp 2>&1 \
+    && grep "PASS: $tst" $tmp >/dev/null 2>&1 \
+    || { echo "FAIL: $tst"; is_OK=false; }
   sed -e "s%$abs_srcdir/%SRCDIR/%" \
       -e "s%\.\./%./%" \
       $tst.log >$file
-  echo "PASS: $tst.test" >>$file
+  $is_OK && {
+    echo "PASS: $tst" >>$file
+    echo "PASS: $tst"
+  } || {
+    echo "FAIL: $tst" >>$file
+    rc=1
+  }
   rm -f $tmp
-  echo "PASS: $tst.test"
 done
 echo "$me: All done"
+exit $rc
+
 
